heat_template_version: queens

parameters:
  imageId:
    type: string
    description: provid image id

ressources:
  image_from_heat:
    type: OS::Glance::WebImage
    properties:
      container_format: bare
      disk_format: iso
      location: https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/alpine-standard-3.14.1-x86_64.iso
      id: {○get_param: Imageid}
